# Generated by Django 6.0.3 on 2026-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('density', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
            ],
        ),
    ]
