# Generated by Django 6.0.3 on 2026-09-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level', models.FloatField()),
                ('ground_level', models.FloatField()),
                ('safety_allowance', models.FloatField()),
                ('barrier_length', models.FloatField()),
                ('barrier_width', models.FloatField()),
                ('barrier_height', models.FloatField()),
                ('barrier_volume', models.FloatField()),
                ('material_quantity', models.FloatField()),
                ('material_cost', models.FloatField()),
                ('labour_cost', models.FloatField()),
                ('equipment_cost', models.FloatField()),
                ('transportation_cost', models.FloatField()),
                ('other_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
